</div>

<footer>
	<div class="container">
		Aluguel de Veiculos 
	</div>
	<script src="jquery.js"></script>
	<script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
	<script src="https://kit.fontawesome.com/166810ef15.js" crossorigin="anonymous"></script>
	<script>
		$(document).ready( function () {
			$('#Veiculos').DataTable();
			$('#Clientes').DataTable();
			$('#Aluguel').DataTable();
		} );
	</script>
</footer>
</body>
</html>